### ISSUE TITLE
You have a duplicated mod error

### ISSUE THREAD

**Issue by Gami3l72** [embeddedt/embeddium#328]
### Bug Description

when having rubidium-mc1.20.1-0.7.1 and embeddium-0.3.21+mc1.20.1 in the same modpack , minecraft thinks they are the same mod , so minecraft crashes with the duplicate mod error.

### Reproduction Steps

1- Create an modpack with forge 1.20.1-47.2.17
2- Put rubidium 1.20.1 version 0.7.1 and embeddium 1.20.1 version 0.3.21 in the same modpack
(idk if that works but it should technically work)

### Log File

https://mclo.gs/l9VsXPG

**Comment by embeddedt** [comment]
This is intended; Embeddium fully replaces Rubidium, and should not be used alongside it.
